### ISSUE TITLE
Zipcode parser

### ISSUE THREAD

**Issue by inveterateliterate** [LaunchPadLab/decanter#128]
## Feature Description
I thought I had posted this before but I can't find it. ln some projects I have written a custom parser to support zip code issues (usually for importing as CSVs will drop leading zeros). If other people have run into this, might be useful enough to add to the gem!

## Suggested Solution
```
module Importers
  class TypeParser::ZipTypeParser < TypeParser
    def parse_val
      val = value.delete('-')
      not_digits unless val.count('0-9') == val.length
      until val.length >= 5 do
        val = '0' + val
      end
      val
    end

    def not_digits
      raise
    end

    def error_message
      "Invalid value for column: #{key}"
    end
  end
end

```

a version written ~5 years ago, could certainly be improved. The idea is first it checks that the numbers are numeric, and second if the number of digits is fewer than 5, assume it's due to dropped leading zeros and tries to add those back.

This zip parser comes with the specific use case of American (or other places with 5 digit zip codes). Options could include passing in the number of digits it should reach if we are aware of similar patterns in other countries.

## Alternatives Considered / Existing Workarounds
Including a custom parser in the app.

## Additional Context
N/A

**Comment by chawes13** [comment]
I'm hesitant to add this to the library for two reasons:
- Zip code formats vary widely between countries
  - E.g., 60654, N0H 2P0, EC4A 3TR ,1081 LA)
- Validation is coupled with parsing
  - In a controller, I think it would be more appropriate for a US zip code of `6065e` to raise `ActiveRecord::RecordInvalid` rather than `Decanter::ParseError`. This separation of concerns would also support using the controller (or model) to leverage a third party location service to perform enhanced zip (or complete address) validation

For the use case you described above, it sounds like the core issue is that leading 0s are getting truncated. That's typically addressed by CSV importing libraries like [SmarterCSV](https://github.com/tilo/smarter_csv). Do you usually roll your own importer or is there another common gem for importing CSVs that doesn't address this issue?

If there are enough use cases out there, I could see the need for a generic `PaddedStringParser`, something along the lines of:
```rb
class AddressDecanter <Decanter::Base
  input :zip, :padded_string, length: 5, pad_string: "0"
end

class PaddedStringParser < ValueParser
  parser do |val, options|
    length = options.fetch(:length)
    pad_string = options.fetch(:pad_string)
    justification_method = options.fetch(:justification, :right) == :right ? :rjust : :ljust
    val.send(justification_method, length, pad_string)
  end
end
```

**Comment by inveterateliterate** [comment]
yes, I agree this zip parser comes with the specific use case of American (or other places with 5 digit zip codes). Options could include passing in the number of digits it should reach if we are aware of similar patterns in other countries.

I know that some of the refactorings of this gem over time have been with a driving principle of decoupling parsing and transformation / validation. While this gem currently still includes instances of coupled decanter parsers, I am aligned with keeping to the principle and by virtue not adding _new_ instances of coupled parsers.

I do really like this abstracted version of a string padded parser!, however to the point above, perhaps that kind of code does better live somewhere else.

Thanks for pointing out that gem - I had not used it nor have I seen it on a project yet and am curious to read more and explore! I have been writing my own importers that essentially come with custom transformers (and reusing those patterns across projects).

To that end, perhaps we have an opportunity to capture guidance and raise visibility on CSV importing patterns: https://www.notion.so/launchpadlab/Data-Imports-aee3afe357b640f69b67772df5bc60af

**Comment by chawes13** [comment]
Both @anthonyjlower and @dianacamacho have experience with `smarter_csv`! DSS was a pretty extensive use case, since the app is very heavily based on manual csv imports
