### ISSUE TITLE
Cast /yes/i to true in Boolean parser

### ISSUE THREAD

**Issue by chawes13** [LaunchPadLab/decanter#97]
Cc @dpikt

**Comment by dpikt** [comment]
Definitely a judgement call. The closest thing I could find to a canonical list of boolean strings is here: https://github.com/rails/rails/blob/master/activemodel/lib/active_model/type/boolean.rb#L37, which doesn't include yes/no. Interestingly, they check for false strings rather than true ones.

This could be accomplished either by adding a custom parser per-project, or by enabling an option on the parser for acceptable strings. Something like:
```rb
input :active, :boolean, trueValues: ['yes', 'Yes']
```
Thoughts?

---
Tangentially related, it might be nice to have a way to globally set defaults for parsers per-app:
```rb
Decanter.config do |config|
  config.default_parser_options.boolean = { trueValues: ['yes', 'Yes'] }
end
```

**Comment by chawes13** [comment]
I also had looked at the Active Model logic. I think it makes sense from the behavior of boolean coercion? E.g., `!!1`, `!!2`, and `!!n` where `n > 0`  are true, whereas only `!!0` is false. I'm hesitant to make that change here though as I think that would be categorized as a breaking change.

My intuition is leading me towards creating a custom `SemanticBoolean` parser and battle testing it on an app before considering it for inclusion in this library

**Comment by chawes13** [comment]
Per the discussion above, closing this issue. May re-address this down the road if the issue pops up again
